apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: amplitude
  namespace: api
spec:
  broker: event-broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: amplitude